# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/grisha/git_testing/jpeg-decoder

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/grisha/git_testing/jpeg-decoder

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/grisha/git_testing/jpeg-decoder/CMakeFiles /home/grisha/git_testing/jpeg-decoder//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/grisha/git_testing/jpeg-decoder/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named jpeg_decoder

# Build rule for target.
jpeg_decoder: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 jpeg_decoder
.PHONY : jpeg_decoder

# fast build rule for target.
jpeg_decoder/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/jpeg_decoder.dir/build.make CMakeFiles/jpeg_decoder.dir/build
.PHONY : jpeg_decoder/fast

decoder.o: decoder.cpp.o
.PHONY : decoder.o

# target to build an object file
decoder.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/jpeg_decoder.dir/build.make CMakeFiles/jpeg_decoder.dir/decoder.cpp.o
.PHONY : decoder.cpp.o

decoder.i: decoder.cpp.i
.PHONY : decoder.i

# target to preprocess a source file
decoder.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/jpeg_decoder.dir/build.make CMakeFiles/jpeg_decoder.dir/decoder.cpp.i
.PHONY : decoder.cpp.i

decoder.s: decoder.cpp.s
.PHONY : decoder.s

# target to generate assembly for a file
decoder.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/jpeg_decoder.dir/build.make CMakeFiles/jpeg_decoder.dir/decoder.cpp.s
.PHONY : decoder.cpp.s

fft.o: fft.cpp.o
.PHONY : fft.o

# target to build an object file
fft.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/jpeg_decoder.dir/build.make CMakeFiles/jpeg_decoder.dir/fft.cpp.o
.PHONY : fft.cpp.o

fft.i: fft.cpp.i
.PHONY : fft.i

# target to preprocess a source file
fft.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/jpeg_decoder.dir/build.make CMakeFiles/jpeg_decoder.dir/fft.cpp.i
.PHONY : fft.cpp.i

fft.s: fft.cpp.s
.PHONY : fft.s

# target to generate assembly for a file
fft.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/jpeg_decoder.dir/build.make CMakeFiles/jpeg_decoder.dir/fft.cpp.s
.PHONY : fft.cpp.s

file_reader.o: file_reader.cpp.o
.PHONY : file_reader.o

# target to build an object file
file_reader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/jpeg_decoder.dir/build.make CMakeFiles/jpeg_decoder.dir/file_reader.cpp.o
.PHONY : file_reader.cpp.o

file_reader.i: file_reader.cpp.i
.PHONY : file_reader.i

# target to preprocess a source file
file_reader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/jpeg_decoder.dir/build.make CMakeFiles/jpeg_decoder.dir/file_reader.cpp.i
.PHONY : file_reader.cpp.i

file_reader.s: file_reader.cpp.s
.PHONY : file_reader.s

# target to generate assembly for a file
file_reader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/jpeg_decoder.dir/build.make CMakeFiles/jpeg_decoder.dir/file_reader.cpp.s
.PHONY : file_reader.cpp.s

huffman.o: huffman.cpp.o
.PHONY : huffman.o

# target to build an object file
huffman.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/jpeg_decoder.dir/build.make CMakeFiles/jpeg_decoder.dir/huffman.cpp.o
.PHONY : huffman.cpp.o

huffman.i: huffman.cpp.i
.PHONY : huffman.i

# target to preprocess a source file
huffman.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/jpeg_decoder.dir/build.make CMakeFiles/jpeg_decoder.dir/huffman.cpp.i
.PHONY : huffman.cpp.i

huffman.s: huffman.cpp.s
.PHONY : huffman.s

# target to generate assembly for a file
huffman.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/jpeg_decoder.dir/build.make CMakeFiles/jpeg_decoder.dir/huffman.cpp.s
.PHONY : huffman.cpp.s

jpeg_decoder.o: jpeg_decoder.cpp.o
.PHONY : jpeg_decoder.o

# target to build an object file
jpeg_decoder.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/jpeg_decoder.dir/build.make CMakeFiles/jpeg_decoder.dir/jpeg_decoder.cpp.o
.PHONY : jpeg_decoder.cpp.o

jpeg_decoder.i: jpeg_decoder.cpp.i
.PHONY : jpeg_decoder.i

# target to preprocess a source file
jpeg_decoder.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/jpeg_decoder.dir/build.make CMakeFiles/jpeg_decoder.dir/jpeg_decoder.cpp.i
.PHONY : jpeg_decoder.cpp.i

jpeg_decoder.s: jpeg_decoder.cpp.s
.PHONY : jpeg_decoder.s

# target to generate assembly for a file
jpeg_decoder.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/jpeg_decoder.dir/build.make CMakeFiles/jpeg_decoder.dir/jpeg_decoder.cpp.s
.PHONY : jpeg_decoder.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/jpeg_decoder.dir/build.make CMakeFiles/jpeg_decoder.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/jpeg_decoder.dir/build.make CMakeFiles/jpeg_decoder.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/jpeg_decoder.dir/build.make CMakeFiles/jpeg_decoder.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... jpeg_decoder"
	@echo "... decoder.o"
	@echo "... decoder.i"
	@echo "... decoder.s"
	@echo "... fft.o"
	@echo "... fft.i"
	@echo "... fft.s"
	@echo "... file_reader.o"
	@echo "... file_reader.i"
	@echo "... file_reader.s"
	@echo "... huffman.o"
	@echo "... huffman.i"
	@echo "... huffman.s"
	@echo "... jpeg_decoder.o"
	@echo "... jpeg_decoder.i"
	@echo "... jpeg_decoder.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

